version: "3.8"
services:
  farmer_service:
    build: ./farmer_service
    ports:
      - "8001:8001"
    depends_on:
      - farmer_db
    environment:
      - DATABASE_URL=postgresql://user:password@farmer_db:5432/farmer_db

  feed_service:
    build: ./feed_service
    ports:
      - "8002:8002"
    depends_on:
      - feed_db
    environment:
      - DATABASE_URL=postgresql://user:password@feed_db:5432/feed_db

  cow_service:
    build: ./cow_service
    ports:
      - "8003:8003"
    depends_on:
      - cow_db
    environment:
      - DATABASE_URL=postgresql://user:password@cow_db:5432/cow_db

  slaughterhouse_service:
    build: ./slaughterhouse_service
    ports:
      - "8004:8004"
    depends_on:
      - slaughterhouse_db
    environment:
      - DATABASE_URL=postgresql://user:password@slaughterhouse_db:5432/slaughterhouse_db

  transaction_service:
    build: ./transaction_service
    ports:
      - "8005:8005"
    depends_on:
      - transaction_db
    environment:
      - DATABASE_URL=postgresql://user:password@transaction_db:5432/transaction_db

  farmer_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=farmer_db
    volumes:
      - farmer_data:/var/lib/postgresql/data

  feed_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feed_db
    volumes:
      - feed_data:/var/lib/postgresql/data

  cow_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cow_db
    volumes:
      - cow_data:/var/lib/postgresql/data

  slaughterhouse_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=slaughterhouse_db
    volumes:
      - slaughterhouse_data:/var/lib/postgresql/data

  transaction_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transaction_db
    volumes:
      - transaction_data:/var/lib/postgresql/data

volumes:
  farmer_data:
  feed_data:
  cow_data:
  slaughterhouse_data:
  transaction_data:
