version: "3.8"
services:
  admin_service:
    build: ./admin_service
    ports:
      - "8000:8000"
    volumes:
      - ./admin_service:/app

  sapi_service:
    build: ./sapi_service
    ports:
      - "8001:8001"
    volumes:
      - ./sapi_service:/app

  peternak_service:
    build: ./peternak_service
    ports:
      - "8002:8002"
    volumes:
      - ./peternak_service:/app
